// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nilesh0729/PixelScribe/internal/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination internal/db/mock/store.go github.com/nilesh0729/PixelScribe/internal/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/nilesh0729/PixelScribe/internal/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CountAttemptsByDictation mocks base method.
func (m *MockStore) CountAttemptsByDictation(ctx context.Context, arg db.CountAttemptsByDictationParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAttemptsByDictation", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAttemptsByDictation indicates an expected call of CountAttemptsByDictation.
func (mr *MockStoreMockRecorder) CountAttemptsByDictation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAttemptsByDictation", reflect.TypeOf((*MockStore)(nil).CountAttemptsByDictation), ctx, arg)
}

// CreateAttempts mocks base method.
func (m *MockStore) CreateAttempts(ctx context.Context, arg db.CreateAttemptsParams) (db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttempts", ctx, arg)
	ret0, _ := ret[0].(db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttempts indicates an expected call of CreateAttempts.
func (mr *MockStoreMockRecorder) CreateAttempts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttempts", reflect.TypeOf((*MockStore)(nil).CreateAttempts), ctx, arg)
}

// CreateAudioDictations mocks base method.
func (m *MockStore) CreateAudioDictations(ctx context.Context, arg db.CreateAudioDictationsParams) (db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAudioDictations", ctx, arg)
	ret0, _ := ret[0].(db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAudioDictations indicates an expected call of CreateAudioDictations.
func (mr *MockStoreMockRecorder) CreateAudioDictations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAudioDictations", reflect.TypeOf((*MockStore)(nil).CreateAudioDictations), ctx, arg)
}

// CreatePerformanceSummary mocks base method.
func (m *MockStore) CreatePerformanceSummary(ctx context.Context, arg db.CreatePerformanceSummaryParams) (db.PerformanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePerformanceSummary", ctx, arg)
	ret0, _ := ret[0].(db.PerformanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePerformanceSummary indicates an expected call of CreatePerformanceSummary.
func (mr *MockStoreMockRecorder) CreatePerformanceSummary(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePerformanceSummary", reflect.TypeOf((*MockStore)(nil).CreatePerformanceSummary), ctx, arg)
}

// CreateSetting mocks base method.
func (m *MockStore) CreateSetting(ctx context.Context, arg db.CreateSettingParams) (db.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetting", ctx, arg)
	ret0, _ := ret[0].(db.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSetting indicates an expected call of CreateSetting.
func (mr *MockStoreMockRecorder) CreateSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetting", reflect.TypeOf((*MockStore)(nil).CreateSetting), ctx, arg)
}

// CreateTextDictations mocks base method.
func (m *MockStore) CreateTextDictations(ctx context.Context, arg db.CreateTextDictationsParams) (db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTextDictations", ctx, arg)
	ret0, _ := ret[0].(db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTextDictations indicates an expected call of CreateTextDictations.
func (mr *MockStoreMockRecorder) CreateTextDictations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTextDictations", reflect.TypeOf((*MockStore)(nil).CreateTextDictations), ctx, arg)
}

// CreateUserTx mocks base method.
func (m *MockStore) CreateUserTx(ctx context.Context, arg db.CreateUsersParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", ctx, arg)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreMockRecorder) CreateUserTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStore)(nil).CreateUserTx), ctx, arg)
}

// CreateUsers mocks base method.
func (m *MockStore) CreateUsers(ctx context.Context, arg db.CreateUsersParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsers", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUsers indicates an expected call of CreateUsers.
func (mr *MockStoreMockRecorder) CreateUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsers", reflect.TypeOf((*MockStore)(nil).CreateUsers), ctx, arg)
}

// DeleteAttempt mocks base method.
func (m *MockStore) DeleteAttempt(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttempt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttempt indicates an expected call of DeleteAttempt.
func (mr *MockStoreMockRecorder) DeleteAttempt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttempt", reflect.TypeOf((*MockStore)(nil).DeleteAttempt), ctx, id)
}

// DeleteAttemptsByDictation mocks base method.
func (m *MockStore) DeleteAttemptsByDictation(ctx context.Context, arg db.DeleteAttemptsByDictationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttemptsByDictation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttemptsByDictation indicates an expected call of DeleteAttemptsByDictation.
func (mr *MockStoreMockRecorder) DeleteAttemptsByDictation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttemptsByDictation", reflect.TypeOf((*MockStore)(nil).DeleteAttemptsByDictation), ctx, arg)
}

// DeleteDictationTx mocks base method.
func (m *MockStore) DeleteDictationTx(ctx context.Context, dictationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDictationTx", ctx, dictationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDictationTx indicates an expected call of DeleteDictationTx.
func (mr *MockStoreMockRecorder) DeleteDictationTx(ctx, dictationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDictationTx", reflect.TypeOf((*MockStore)(nil).DeleteDictationTx), ctx, dictationID)
}

// DeleteDictations mocks base method.
func (m *MockStore) DeleteDictations(ctx context.Context, title sql.NullString) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDictations", ctx, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDictations indicates an expected call of DeleteDictations.
func (mr *MockStoreMockRecorder) DeleteDictations(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDictations", reflect.TypeOf((*MockStore)(nil).DeleteDictations), ctx, title)
}

// DeletePerformanceSummary mocks base method.
func (m *MockStore) DeletePerformanceSummary(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePerformanceSummary", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePerformanceSummary indicates an expected call of DeletePerformanceSummary.
func (mr *MockStoreMockRecorder) DeletePerformanceSummary(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePerformanceSummary", reflect.TypeOf((*MockStore)(nil).DeletePerformanceSummary), ctx, id)
}

// DeleteSetting mocks base method.
func (m *MockStore) DeleteSetting(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSetting", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSetting indicates an expected call of DeleteSetting.
func (mr *MockStoreMockRecorder) DeleteSetting(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSetting", reflect.TypeOf((*MockStore)(nil).DeleteSetting), ctx, id)
}

// DeleteUsers mocks base method.
func (m *MockStore) DeleteUsers(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsers", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsers indicates an expected call of DeleteUsers.
func (mr *MockStoreMockRecorder) DeleteUsers(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsers", reflect.TypeOf((*MockStore)(nil).DeleteUsers), ctx, username)
}

// GetAttemptById mocks base method.
func (m *MockStore) GetAttemptById(ctx context.Context, id int64) (db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttemptById", ctx, id)
	ret0, _ := ret[0].(db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttemptById indicates an expected call of GetAttemptById.
func (mr *MockStoreMockRecorder) GetAttemptById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttemptById", reflect.TypeOf((*MockStore)(nil).GetAttemptById), ctx, id)
}

// GetDictation mocks base method.
func (m *MockStore) GetDictation(ctx context.Context, id int64) (db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictation", ctx, id)
	ret0, _ := ret[0].(db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictation indicates an expected call of GetDictation.
func (mr *MockStoreMockRecorder) GetDictation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictation", reflect.TypeOf((*MockStore)(nil).GetDictation), ctx, id)
}

// GetDictationsByTitle mocks base method.
func (m *MockStore) GetDictationsByTitle(ctx context.Context, title sql.NullString) (db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictationsByTitle", ctx, title)
	ret0, _ := ret[0].(db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictationsByTitle indicates an expected call of GetDictationsByTitle.
func (mr *MockStoreMockRecorder) GetDictationsByTitle(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictationsByTitle", reflect.TypeOf((*MockStore)(nil).GetDictationsByTitle), ctx, title)
}

// GetLatestAttempt mocks base method.
func (m *MockStore) GetLatestAttempt(ctx context.Context, arg db.GetLatestAttemptParams) (db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAttempt", ctx, arg)
	ret0, _ := ret[0].(db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAttempt indicates an expected call of GetLatestAttempt.
func (mr *MockStoreMockRecorder) GetLatestAttempt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAttempt", reflect.TypeOf((*MockStore)(nil).GetLatestAttempt), ctx, arg)
}

// GetPerformanceSummaryByID mocks base method.
func (m *MockStore) GetPerformanceSummaryByID(ctx context.Context, id int64) (db.PerformanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerformanceSummaryByID", ctx, id)
	ret0, _ := ret[0].(db.PerformanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerformanceSummaryByID indicates an expected call of GetPerformanceSummaryByID.
func (mr *MockStoreMockRecorder) GetPerformanceSummaryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerformanceSummaryByID", reflect.TypeOf((*MockStore)(nil).GetPerformanceSummaryByID), ctx, id)
}

// GetPerformanceSummaryByUserAndDictation mocks base method.
func (m *MockStore) GetPerformanceSummaryByUserAndDictation(ctx context.Context, arg db.GetPerformanceSummaryByUserAndDictationParams) (db.PerformanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerformanceSummaryByUserAndDictation", ctx, arg)
	ret0, _ := ret[0].(db.PerformanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerformanceSummaryByUserAndDictation indicates an expected call of GetPerformanceSummaryByUserAndDictation.
func (mr *MockStoreMockRecorder) GetPerformanceSummaryByUserAndDictation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerformanceSummaryByUserAndDictation", reflect.TypeOf((*MockStore)(nil).GetPerformanceSummaryByUserAndDictation), ctx, arg)
}

// GetSettingByID mocks base method.
func (m *MockStore) GetSettingByID(ctx context.Context, id int64) (db.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingByID", ctx, id)
	ret0, _ := ret[0].(db.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingByID indicates an expected call of GetSettingByID.
func (mr *MockStoreMockRecorder) GetSettingByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingByID", reflect.TypeOf((*MockStore)(nil).GetSettingByID), ctx, id)
}

// GetSettingByUserID mocks base method.
func (m *MockStore) GetSettingByUserID(ctx context.Context, userID sql.NullInt64) (db.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingByUserID", ctx, userID)
	ret0, _ := ret[0].(db.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingByUserID indicates an expected call of GetSettingByUserID.
func (mr *MockStoreMockRecorder) GetSettingByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingByUserID", reflect.TypeOf((*MockStore)(nil).GetSettingByUserID), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockStore) GetUsers(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockStoreMockRecorder) GetUsers(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockStore)(nil).GetUsers), ctx, username)
}

// ListAttemptsByDictation mocks base method.
func (m *MockStore) ListAttemptsByDictation(ctx context.Context, dictationID sql.NullInt64) ([]db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttemptsByDictation", ctx, dictationID)
	ret0, _ := ret[0].([]db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttemptsByDictation indicates an expected call of ListAttemptsByDictation.
func (mr *MockStoreMockRecorder) ListAttemptsByDictation(ctx, dictationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttemptsByDictation", reflect.TypeOf((*MockStore)(nil).ListAttemptsByDictation), ctx, dictationID)
}

// ListAttemptsByUser mocks base method.
func (m *MockStore) ListAttemptsByUser(ctx context.Context, userID sql.NullInt64) ([]db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttemptsByUser", ctx, userID)
	ret0, _ := ret[0].([]db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttemptsByUser indicates an expected call of ListAttemptsByUser.
func (mr *MockStoreMockRecorder) ListAttemptsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttemptsByUser", reflect.TypeOf((*MockStore)(nil).ListAttemptsByUser), ctx, userID)
}

// ListAudioDictations mocks base method.
func (m *MockStore) ListAudioDictations(ctx context.Context, userID sql.NullInt64) ([]db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAudioDictations", ctx, userID)
	ret0, _ := ret[0].([]db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAudioDictations indicates an expected call of ListAudioDictations.
func (mr *MockStoreMockRecorder) ListAudioDictations(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAudioDictations", reflect.TypeOf((*MockStore)(nil).ListAudioDictations), ctx, userID)
}

// ListDictationsByUser mocks base method.
func (m *MockStore) ListDictationsByUser(ctx context.Context, userID sql.NullInt64) ([]db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDictationsByUser", ctx, userID)
	ret0, _ := ret[0].([]db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDictationsByUser indicates an expected call of ListDictationsByUser.
func (mr *MockStoreMockRecorder) ListDictationsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDictationsByUser", reflect.TypeOf((*MockStore)(nil).ListDictationsByUser), ctx, userID)
}

// ListPerformanceSummaryByUser mocks base method.
func (m *MockStore) ListPerformanceSummaryByUser(ctx context.Context, userID sql.NullInt64) ([]db.PerformanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPerformanceSummaryByUser", ctx, userID)
	ret0, _ := ret[0].([]db.PerformanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPerformanceSummaryByUser indicates an expected call of ListPerformanceSummaryByUser.
func (mr *MockStoreMockRecorder) ListPerformanceSummaryByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPerformanceSummaryByUser", reflect.TypeOf((*MockStore)(nil).ListPerformanceSummaryByUser), ctx, userID)
}

// ListTextDictations mocks base method.
func (m *MockStore) ListTextDictations(ctx context.Context, userID sql.NullInt64) ([]db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTextDictations", ctx, userID)
	ret0, _ := ret[0].([]db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTextDictations indicates an expected call of ListTextDictations.
func (mr *MockStoreMockRecorder) ListTextDictations(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTextDictations", reflect.TypeOf((*MockStore)(nil).ListTextDictations), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx, arg)
}

// RecentAttemptsByUser mocks base method.
func (m *MockStore) RecentAttemptsByUser(ctx context.Context, arg db.RecentAttemptsByUserParams) ([]db.PerformanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentAttemptsByUser", ctx, arg)
	ret0, _ := ret[0].([]db.PerformanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentAttemptsByUser indicates an expected call of RecentAttemptsByUser.
func (mr *MockStoreMockRecorder) RecentAttemptsByUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentAttemptsByUser", reflect.TypeOf((*MockStore)(nil).RecentAttemptsByUser), ctx, arg)
}

// SubmitAttemptTx mocks base method.
func (m *MockStore) SubmitAttemptTx(ctx context.Context, arg db.CreateAttemptsParams) (db.SubmitAttemptTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitAttemptTx", ctx, arg)
	ret0, _ := ret[0].(db.SubmitAttemptTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitAttemptTx indicates an expected call of SubmitAttemptTx.
func (mr *MockStoreMockRecorder) SubmitAttemptTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAttemptTx", reflect.TypeOf((*MockStore)(nil).SubmitAttemptTx), ctx, arg)
}

// UpdateAttemptAccuracy mocks base method.
func (m *MockStore) UpdateAttemptAccuracy(ctx context.Context, arg db.UpdateAttemptAccuracyParams) (db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttemptAccuracy", ctx, arg)
	ret0, _ := ret[0].(db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAttemptAccuracy indicates an expected call of UpdateAttemptAccuracy.
func (mr *MockStoreMockRecorder) UpdateAttemptAccuracy(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttemptAccuracy", reflect.TypeOf((*MockStore)(nil).UpdateAttemptAccuracy), ctx, arg)
}

// UpdateDictation mocks base method.
func (m *MockStore) UpdateDictation(ctx context.Context, arg db.UpdateDictationParams) (db.Dictation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDictation", ctx, arg)
	ret0, _ := ret[0].(db.Dictation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDictation indicates an expected call of UpdateDictation.
func (mr *MockStoreMockRecorder) UpdateDictation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDictation", reflect.TypeOf((*MockStore)(nil).UpdateDictation), ctx, arg)
}

// UpdatePerformanceSummary mocks base method.
func (m *MockStore) UpdatePerformanceSummary(ctx context.Context, arg db.UpdatePerformanceSummaryParams) (db.PerformanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePerformanceSummary", ctx, arg)
	ret0, _ := ret[0].(db.PerformanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePerformanceSummary indicates an expected call of UpdatePerformanceSummary.
func (mr *MockStoreMockRecorder) UpdatePerformanceSummary(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePerformanceSummary", reflect.TypeOf((*MockStore)(nil).UpdatePerformanceSummary), ctx, arg)
}

// UpdateSetting mocks base method.
func (m *MockStore) UpdateSetting(ctx context.Context, arg db.UpdateSettingParams) (db.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSetting", ctx, arg)
	ret0, _ := ret[0].(db.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSetting indicates an expected call of UpdateSetting.
func (mr *MockStoreMockRecorder) UpdateSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSetting", reflect.TypeOf((*MockStore)(nil).UpdateSetting), ctx, arg)
}

// UpdateUsers mocks base method.
func (m *MockStore) UpdateUsers(ctx context.Context, arg db.UpdateUsersParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsers", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUsers indicates an expected call of UpdateUsers.
func (mr *MockStoreMockRecorder) UpdateUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsers", reflect.TypeOf((*MockStore)(nil).UpdateUsers), ctx, arg)
}

// UserAggregatePerformance mocks base method.
func (m *MockStore) UserAggregatePerformance(ctx context.Context) ([]db.UserAggregatePerformanceRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAggregatePerformance", ctx)
	ret0, _ := ret[0].([]db.UserAggregatePerformanceRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserAggregatePerformance indicates an expected call of UserAggregatePerformance.
func (mr *MockStoreMockRecorder) UserAggregatePerformance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAggregatePerformance", reflect.TypeOf((*MockStore)(nil).UserAggregatePerformance), ctx)
}
