CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" text,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE "dictations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "title" varchar,
  "type" varchar,
  "content" text,
  "audio_url" text,
  "language" varchar,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE "attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "dictation_id" bigint,
  "typed_text" text,
  "attempt_no" int,
  "total_words" int,
  "correct_words" int,
  "grammatical_errors" int,
  "spelling_errors" int,
  "case_errors" int,
  "accuracy" float,
  "comparison_data" jsonb,
  "time_spent" float,
  "created_at" timestamp DEFAULT NOW()
);

CREATE TABLE "performance_summary" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "dictation_id" bigint,
  "total_attempts" int,
  "best_accuracy" float,
  "average_accuracy" float,
  "average_time" float,
  "last_attempt_at" timestamp
);

CREATE TABLE "settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "default_voice" varchar,
  "default_speed" float,
  "highlight_color_grammar" varchar,
  "highlight_color_spelling" varchar,
  "highlight_color_case" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "dictations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "attempts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "attempts" ADD FOREIGN KEY ("dictation_id") REFERENCES "dictations" ("id");

ALTER TABLE "performance_summary" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "performance_summary" ADD FOREIGN KEY ("dictation_id") REFERENCES "dictations" ("id");

ALTER TABLE "settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
